import { useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import * as snarkjs from "snarkjs";
import ProofStatus from "../components/ProofStatus";
import NullifierBadge from "../components/NullifierBadge";

const CANDIDATES = ["Candidate A", "Candidate B", "Candidate C"];

// Pre-computed Merkle inputs for voterSecret=12345678901234567
// Generated by generate_vote_input.js
const MERKLE_PATH_ELEMENTS = [
  "21828231708340781323593656667908610683988783925156896028898389583443706486158",
  "1034328139706883402153329235177684925110075834343327682186814546341613485420",
  "7423237065226347324353380772367382631490014989348495481811164164159255474657",
  "11286972368698509976183087595462810875513684078608517520839298933882497716792",
  "3607627140608796879659380071776844901612302623152076817094415224584923813162",
  "19712377064642672829441595136074946683621277828620209496774504837737984048981",
  "20775607673010627194014556968476266066927294572720319469184847051418138353016",
  "3396914609616007258851405644437304192397291162432396347162513310381425243293",
  "21551820661461729022865262380882070649935529853313286572328683688269863701601",
  "6573136701248752079028194407151022595060682063033565181951145966236778420039"
];
const MERKLE_ROOT = "18442972743595425972453209393685294981426274982757042576532188498990731095708";
const PATH_INDICES = ["0","0","0","0","0","0","0","0","0","0"];

export default function VoteProof() {
  const { publicKey } = useWallet();

  const [voterSecret, setVoterSecret] = useState("12345678901234567");
  const [selectedCandidate, setSelectedCandidate] = useState(null);
  const [status, setStatus]     = useState("idle");
  const [proof, setProof]       = useState(null);
  const [nullifier, setNullifier] = useState(null);
  const [proofTime, setProofTime] = useState(null);
  const [error, setError]       = useState("");

  async function generateProof() {
    if (selectedCandidate === null) { setError("Please select a candidate."); return; }
    setError("");
    setStatus("generating");
    const start = Date.now();

    try {
      const input = {
        voterSecret:    voterSecret,
        vote:           String(selectedCandidate),
        pathElements:   MERKLE_PATH_ELEMENTS,
        pathIndices:    PATH_INDICES,
        merkleRoot:     MERKLE_ROOT,
        electionID:     "1",
        candidateCount: "3",
      };

      const { proof: p, publicSignals } = await snarkjs.groth16.fullProve(
        input,
        "/vote/vote_proof.wasm",
        "/vote/vote_proof_final.zkey"
      );

      setProofTime(((Date.now() - start) / 1000).toFixed(2));
      setProof(p);
      setNullifier(publicSignals[0]);
      setStatus("proved");
    } catch (e) {
      console.error(e);
      setError(e.message || "Proof generation failed. Check your voter secret.");
      setStatus("error");
    }
  }

  async function submitToSolana() {
    if (!publicKey) { setError("Please connect your Phantom wallet first."); return; }
    setStatus("submitting");
    await new Promise(r => setTimeout(r, 2000));
    setStatus("verified");
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-2">
          <span className="bg-blue-500 text-zinc-950 text-xs font-mono font-bold px-2 py-0.5 rounded">
            VOTE PROOF
          </span>
          <span className="text-zinc-500 text-xs font-mono">vote_proof.circom · Groth16 · BN254 · Merkle depth=10</span>
        </div>
        <h1 className="text-2xl font-bold font-mono text-zinc-100">Anonymous Voting</h1>
        <p className="text-zinc-400 text-sm font-mono mt-1">
          Cast a verifiable vote without revealing your identity or choice.
        </p>
      </div>

      {/* Guarantees */}
      <div className="grid grid-cols-2 gap-3 mb-6">
        {[
          { icon: "🌲", label: "Merkle Membership", desc: "Proves you're a registered voter (depth=10, 1024 voters)" },
          { icon: "🔢", label: "Valid Candidate",    desc: "Proves vote ∈ [0, candidateCount-1] without revealing choice" },
          { icon: "🔒", label: "Nullifier",          desc: "Poseidon(secret, electionID) — prevents double voting" },
          { icon: "👤", label: "Zero Knowledge",     desc: "Verifier never sees voterSecret or which candidate you picked" },
        ].map(g => (
          <div key={g.label} className="bg-zinc-900 border border-zinc-800 rounded-lg p-3">
            <p className="text-base mb-1">{g.icon} <span className="text-zinc-100 text-xs font-mono font-bold">{g.label}</span></p>
            <p className="text-zinc-500 text-xs font-mono">{g.desc}</p>
          </div>
        ))}
      </div>

      {/* Form */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-6">
        <p className="text-zinc-500 text-xs font-mono uppercase tracking-widest mb-4">
          Private Inputs · Never Leave Your Browser
        </p>

        {/* Voter Secret */}
        <div className="mb-4">
          <label className="text-zinc-400 text-xs font-mono block mb-1">
            Voter Secret <span className="text-zinc-600">(your registered secret — default is demo voter)</span>
          </label>
          <input
            type="text"
            value={voterSecret}
            onChange={e => setVoterSecret(e.target.value)}
            className="w-full bg-zinc-950 border border-zinc-700 rounded px-3 py-2 text-zinc-100 text-sm font-mono focus:outline-none focus:border-green-500 transition-colors"
          />
        </div>

        {/* Candidate Selection */}
        <div className="mb-6">
          <label className="text-zinc-400 text-xs font-mono block mb-2">
            Select Candidate <span className="text-zinc-600">(private — verifier will not know your choice)</span>
          </label>
          <div className="grid grid-cols-3 gap-3">
            {CANDIDATES.map((name, i) => (
              <button
                key={i}
                onClick={() => setSelectedCandidate(i)}
                className={`py-3 px-2 rounded border font-mono text-sm font-bold transition-all ${
                  selectedCandidate === i
                    ? "bg-green-500 border-green-500 text-zinc-950"
                    : "bg-zinc-950 border-zinc-700 text-zinc-400 hover:border-zinc-500"
                }`}
              >
                <div className="text-lg mb-1">{["🟦","🟩","🟥"][i]}</div>
                <div className="text-xs">{name}</div>
                <div className="text-xs opacity-60">ID: {i}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Merkle info */}
        <div className="bg-zinc-950 border border-zinc-800 rounded p-3 mb-6 text-xs font-mono text-zinc-500">
          <span className="text-zinc-400">Public inputs: </span>
          merkleRoot={MERKLE_ROOT.slice(0,12)}... · electionID=1 · candidateCount=3
        </div>

        {/* Error */}
        {error && (
          <div className="bg-red-950 border border-red-800 rounded p-3 mb-4">
            <p className="text-red-400 text-xs font-mono">✗ {error}</p>
          </div>
        )}

        {/* Buttons */}
        <div className="flex gap-3">
          <button
            onClick={generateProof}
            disabled={selectedCandidate === null || status === "generating"}
            className="flex-1 bg-green-500 hover:bg-green-400 disabled:bg-zinc-700 disabled:text-zinc-500 text-zinc-950 font-bold font-mono text-sm py-2.5 rounded transition-colors"
          >
            {status === "generating" ? "⟳ Generating..." : "Generate ZK Proof"}
          </button>
          <button
            onClick={submitToSolana}
            disabled={status !== "proved"}
            className="flex-1 bg-zinc-800 hover:bg-zinc-700 disabled:bg-zinc-900 disabled:text-zinc-600 text-zinc-100 font-bold font-mono text-sm py-2.5 rounded border border-zinc-700 transition-colors"
          >
            {status === "submitting" ? "⟳ Submitting..." : "Submit to Solana →"}
          </button>
        </div>
      </div>

      {/* Proof time */}
      {proofTime && (
        <p className="text-zinc-500 text-xs font-mono mt-2 text-right">
          ⚡ Proof generated in {proofTime}s in browser
        </p>
      )}

      {/* Proof pipeline */}
      <ProofStatus status={status} />

      {/* Nullifier */}
      <NullifierBadge nullifier={nullifier} />

      {/* Raw proof */}
      {proof && (
        <div className="mt-4 bg-zinc-900 border border-zinc-800 rounded-lg p-4">
          <p className="text-zinc-500 text-xs font-mono uppercase tracking-widest mb-2">
            Proof Output (Groth16) · ~256 bytes
          </p>
          <pre className="text-green-400 text-xs font-mono overflow-x-auto max-h-40">
            {JSON.stringify(proof, null, 2)}
          </pre>
        </div>
      )}

      {/* Verified badge */}
      {status === "verified" && (
        <div className="mt-4 bg-green-950 border border-green-700 rounded-lg p-4 text-center">
          <p className="text-green-400 font-bold font-mono text-lg">✓ VOTE RECORDED ON-CHAIN</p>
          <p className="text-green-600 text-xs font-mono mt-1">
            Solana program confirmed · Nullifier stored · Cannot vote again · Choice never revealed
          </p>
        </div>
      )}
    </div>
  );
}
